version: '3.3'

services:
  wearhouse:
    build:
      context: .   # Path to the folder containing the Dockerfile for wearhouse
      dockerfile: Dockerfile2
    container_name: wearhouse-container
    command: /app/build/Wearhouse  # Command to run the wearhouse
    networks:
      mynetwork:
        ipv4_address: 172.18.0.2
  shop:
    build:
      context: .   # Path to the folder containing the Dockerfile for shop
      dockerfile: Dockerfile1
    container_name: shop-container
    entrypoint: ["sh", "-c", "sleep 3 && /app/build/Shop"]  # Sleep for 10 seconds before starting
    depends_on:
      - wearhouse
    networks:
      mynetwork:
        ipv4_address: 172.18.0.3

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: "172.18.0.0/16"
